### ISSUE TITLE
crontab, update & merge duplicate

### ISSUE THREAD

**Issue by alsyundawy** [ngandrass/ufw-ipset-blocklist-autoupdate#3]
hi, once again I thank you very much for your hard work, I really appreciate your dedication. but I still have a question, which is as below

1. how does set run in crontab so it runs fine
2. When the update option does the list merge the previous lists or delete the old one then update the new list
3. If it's a shame to use multiple lists according to what's intruded on in the readme, will it result in duplicate IPs & conditions. how to deal with this incident

sorry for my ignorance, hopefully in the future it will get better and keep going

**Comment by ngandrass** [comment]
> 1. how does set run in crontab so it runs fine

You first should execute the `update-ip-blocklists.sh` script once to create all ipsets for the blocklists you would like to use by supplying a `-l "<Blocklist Name> <Blocklist URL>"` argument for each blocklist. Example:
```
./update-ip-blocklists.sh -l "blocklist https://lists.blocklist.de/lists/all.txt" -l "spamhaus https://www.spamhaus.org/drop/drop.txt" -l "spamhaus6 https://www.spamhaus.org/drop/dropv6.txt"
```

You then add this command to the `crontab` of your system. How this is performed in detail depends on your particular system. Usually you can edit your crontab via `crontab -e` or by editing the file `/etc/crontab`. Otherwise Google will surely help with your specific system.

You need to execute the script daily. Example:
```
@daily /full/path/to/update-ip-blocklists.sh -l "blocklist https://lists.blocklist.de/lists/all.txt" -l "spamhaus https://www.spamhaus.org/drop/drop.txt" -l "spamhaus6 https://www.spamhaus.org/drop/dropv6.txt"
```

You need to replace the `/full/path/to/update-ip-blocklists.sh` with the path where you put the script on your machine.

-----

> 2. When the update option does the list merge the previous lists or delete the old one then update the new list

As blocklists usually unblock IPs after a certain amount of time, these need to be cleared from our local lists as well. Therefore, lists will always be replaced.

The script handles this atomically by creating a new temporary ipset during the update cycle and replaces the existing ipset with the updated one. The old ipset is then deleted. This ensures, that the server is protected even during the update cycle :)

-----

> 3. If it's a shame to use multiple lists according to what's intruded on in the readme, will it result in duplicate IPs & conditions. how to deal with this incident

If multiple lists block one IP address, all affected ipsets will include this IP. This is not problematic and directly handled by ipset and iptables. You don't need to worry about it. The IP will be blocked as long as it is listed on at least one active blocklist.

-----

I wish you success in deploying the script on you machines :+1:

**Comment by alsyundawy** [comment]
thx, appreciate . i will try to my machine. 

once again I thank you very much for your hard work
